name: spring-security-simple-oidc-login

services:
  dex:
    image: "dexidp/dex:v2.37.0"
    deploy:
      replicas: 1
    configs:
      - source: dex_config
        target: /opt/config/dex.yml
    ports:
      - "5556:5556"
    command:
      - dex
      - serve
      - /opt/config/dex.yml

configs:
  dex_config:
    content: |
      issuer: "http://localhost:5556"
      storage:
        type: sqlite3
        config:
          file: /etc/dex/dex.db
      web:
        http: 0.0.0.0:5556
      staticClients:
        - id: dex-client-id
          redirectURIs:
            - "http://127.0.0.1:8080/login/oauth2/code/dex"
            - "http://localhost:8080/login/oauth2/code/dex"
          name: 'Base application'
          secret: dex-client-secret
          grant_types:
            - authorization_code
            - client_credentials
      enablePasswordDB: true
      staticPasswords:
        - email: "user@example.com"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # "password"
          username: "user"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
